services:
  - type: web
    name: gabryelle-server
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18.20.4"
    autoDeploy: true
